---
- hosts: all
  become: yes
  tasks:
  - name: des webserver install on ubuntu(apache2)
    apt:
     name: apache2
     state: present
  - name: des webserver apache2 service started
    service:
     name: apache2
     state: started