---
- hosts: webservers
  become: yes
  tasks:
  - name:  install webserver on Ubuntu(apache2)
    apt:
      name: "{{webserveronubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: start webserver on Ubuntu(apache2)
    service: 
      name: "{{webserveronubuntu}}"
      state: started
    when: ansible_os_family =="Debian"
  

  - name: install webserver on rehat (httpd)
    yum:
      name: "{{webserveronredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on rehat
    service:
      name: "{{webserveronredhat}}"
      state: started
    when: ansible_os_family =="RedHat"